{% set name = "sktime" %}
{% set version = "0.40.0" %}

package:
  name: sktime-suite
  version: {{ version }}

source:
  url: https://github.com/sktime/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a3ca4588a7de6e9a205c9e9d3b17faa9b12ed27c2cf1d30a73b523e00f651c2e

build:
  number: 0
  skip: true  # [py<39 or py>314]

# This section is required to correctly rerender skip statement
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
  run:
    - python

outputs:
  - name: sktime
    script: build_script.sh  # [unix]
    script: build_script.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        - setuptools
        - wheel
        - toml
        - python-build
      run:
        - python
        - joblib >=1.2.0,<1.6
        - numpy >=1.21.0,<2.4
        - pandas >=1.1.0,<2.4.0
        - packaging
        - scikit-base >=0.4.4,<0.14.0
        - scikit-learn >=0.24.0,<1.8.0
        - scipy >=1.2.0,<2.0.0
      run_constrained:
        - gluonts >=0.9.0
        - hmmlearn >=0.2.7
        - matplotlib-base >=3.3.2
        - numba >=0.53
        - pmdarima >=1.8.0,!=1.8.1,<3.0.0
        - prophet >=1.1
        - pycatch22 >=0.4,<0.4.6
        - pyod >=0.8.0
        - scikit-posthocs >=0.6.5
        - seaborn >=0.11.0
        - statsforecast >=0.5.2,<2.1.0
        - statsmodels >=0.12.1
        - tsfresh >=0.17.0
        - tslearn >=0.5.2,<0.7.0
    test:
      requires:
        - pip
        - pytest
      commands:
        - pip check
      imports:
        - sktime
        - sktime.classification
        - sktime.datasets
        - sktime.distances
        - sktime.forecasting
        - sktime.performance_metrics
        - sktime.regression
        - sktime.series_as_features
        - sktime.transformations
        - sktime.utils

  - name: sktime-all-extras
    build:
      #FIXME: Extras environment not resolvable on aarch. Needs someone with
      #arm machine to tests.
      skip: true  # [aarch64]
      noarch: python
    requirements:
      run:
        - python
        - {{ pin_subpackage("sktime", max_pin='x.x.x') }}
        - arch-py
        - cloudpickle
        - dask
        - dtw-python
        - h5py
        # - hmmlearn  # not on CF
        - holidays
        # - gluonts  # not on CF
        - matplotlib-base
        - numba >=0.53
        - prophet
        - pycatch22
        - pyod
        # - scikit-optimize  # excluding due to dependency conflicts
        - scikit-posthocs
        - seaborn
        # - seasonal  # not on CF
        - statsforecast
        - tsfresh
        - tslearn
        - xarray

    test:
      requires:
        - pip
        - pytest
      imports:
        - sktime
        - sktime.classification
        - sktime.datasets
        - sktime.distances
        - sktime.forecasting
        - sktime.performance_metrics
        - sktime.regression
        - sktime.series_as_features
        - sktime.transformations
        - sktime.utils

about:
  home: https://github.com/sktime/sktime
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A unified framework for machine learning with time series
  doc_url: https://www.sktime.net/en/latest/
  dev_url: https://github.com/sktime/sktime

extra:
  recipe-maintainers:
    - yarnabrina
    - fkiraly
    - dhirschfeld
    - freddyaboulton
