{% set name = "sktime" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alan-turing-institute/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f7eb20db2a8f2783eb9026a54faeec26077e4af5cdb8da4486f3e097bac0eebf

build:
  number: 0
  skip: true  # [py>39]


outputs:
  - name: sktime
    script: build_script.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - llvm-openmp  # [osx]
      host:
        - python
        - cython >=0.29
        - numba >=0.50,<0.55
        - numpy 1.19.*
        - pandas >=1.1.0,<1.4
        - pip
        - setuptools
        - scikit-learn >=0.24.0
        - statsmodels >=0.12.1
        - wheel
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - pandas >=1.1.0,<1.4
        - scikit-learn >=0.24.0
        - statsmodels >=0.12.1
        - numba >=0.50,<0.55
      run_constrained:
        - matplotlib-base >=3.3.2
        - pmdarima >=1.8.0,!=1.8.1
        - scikit-posthocs >=0.6.5
        - seaborn >=0.11.0
        - tsfresh >=0.17.0
        - hcrystalball >=0.1.9
        - stumpy >=1.5.1
        - fbprophet >=0.7.1
    test:
      imports:
        - sktime
        - sktime.classification
        - sktime.datasets
        - sktime.distances
        - sktime.forecasting
        - sktime.performance_metrics
        - sktime.regression
        - sktime.series_as_features
        - sktime.transformations
        - sktime.utils

  - name: sktime-all-extras
    requirements:
      run:
        - {{ pin_subpackage("sktime", max_pin="x.x.x.x") }}
        - matplotlib-base >=3.3.2
        - pmdarima >=1.8.0,!=1.8.1  # [not win and py<=38]
        - scikit-posthocs >=0.6.5
        - seaborn >=0.11.0
        - tsfresh >=0.17.0
        # - catch22 >=0.1.0
        - hcrystalball >=0.1.9
        - stumpy >=1.5.1
        # - tbats >=1.1.0
        - fbprophet >=0.7.1  # [py<=38]
        - python
    test:
      imports:
        - sktime
        - sktime.classification
        - sktime.datasets
        - sktime.distances
        - sktime.forecasting
        - sktime.performance_metrics
        - sktime.regression
        - sktime.series_as_features
        - sktime.transformations
        - sktime.utils

about:
  home: https://github.com/alan-turing-institute/sktime
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A unified framework for machine learning with time series
  doc_url: https://www.sktime.org/en/latest/
  dev_url: https://github.com/alan-turing-institute/sktime

extra:
  recipe-maintainers:
    - dhirschfeld
    - mloning
