{% set name = "sktime" %}
{% set version = "0.12.1" %}

package:
  name: sktime-suite
  version: {{ version }}

source:
  url: https://github.com/alan-turing-institute/{{ name }}/archive/v.{{ version }}.tar.gz
  sha256: 0e39ce6f7bbe59e3013a3a5f756aa6234f93a570ad6a1cfacebf78872b461529

build:
  number: 2
  skip: true  # [(py==37 and aarch64)]
  skip: true  # [py<37 or py>39]

# This section is required to correctly rerender skip statement
requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: sktime
    script: build_script.sh   # [unix]
    script: build_script.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        - setuptools
        - wheel
        - toml
        - build
      run:
        - python
        - deprecated >=1.2.13
        - numpy >=1.21.0,<1.22
        - pandas >=1.1.0,<1.5
        - numba >=0.53
        - scikit-learn >=0.24.0,<1.2.0
        - statsmodels >=0.12.1
        - scipy <1.9.0
      run_constrained:
        - dtw-python
        - esig ==0.9.7
        - filterpy >=1.4.5
        - hcrystalball >=0.1.9
        - matplotlib-base >=3.3.2
        - pmdarima >=1.8.0,!=1.8.1
        - prophet >=1.0,<1.1
        - pykalman >=0.9.5
        - pyod >=0.8.0
        - pystan ==2.19.1.1
        - scikit-posthocs >=0.6.5
        - seaborn >=0.11.0
        - statsforecast>=0.5.2
        - stumpy >=1.5.1
        - tbats >=1.1.0
        - tensorflow
        - tensorflow-probability
        - tsfresh >=0.17.0
        - tslearn >=0.5.2
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - sktime
        - sktime.classification
        - sktime.datasets
        - sktime.distances
        - sktime.forecasting
        - sktime.performance_metrics
        - sktime.regression
        - sktime.series_as_features
        - sktime.transformations
        - sktime.utils

  - name: sktime-all-extras
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("sktime", exact=True) }}
        - matplotlib-base
        - pmdarima  # [not win and py<=38]
        - prophet   # [not aarch64 and not linux and py>37]
        - pykalman
        - scikit-posthocs
        - seaborn
        - stumpy
        - tbats
        - tsfresh
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - sktime
        - sktime.classification
        - sktime.datasets
        - sktime.distances
        - sktime.forecasting
        - sktime.performance_metrics
        - sktime.regression
        - sktime.series_as_features
        - sktime.transformations
        - sktime.utils

about:
  home: https://github.com/alan-turing-institute/sktime
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A unified framework for machine learning with time series
  doc_url: https://www.sktime.org/en/latest/
  dev_url: https://github.com/alan-turing-institute/sktime

extra:
  recipe-maintainers:
    - fkiraly
    - dhirschfeld
    - freddyaboulton
    - lmmentel
    - mloning
