{% set name = "sktime" %}
{% set version = "0.16.0" %}

package:
  name: sktime-suite
  version: {{ version }}

source:
  url: https://github.com/alan-turing-institute/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fd20eab22e138271b2af9b78f3140c469df8505f88cf951a90aacce08839ceee

build:
  number: 0
  skip: true  # [(py==37 and aarch64)]
  skip: true  # [py<37 or py>39]

# This section is required to correctly rerender skip statement
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
  run:
    - python

outputs:
  - name: sktime
    script: build_script.sh  # [unix]
    script: build_script.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        - setuptools
        - wheel
        - toml
        - python-build
      run:
        - python
        - deprecated >=1.2.13
        - numpy >=1.21.0,<1.25
        - pandas >=1.1.0,<1.6.0
        - numba >=0.55
        - scikit-learn >=0.24.0,<1.3.0
        - statsmodels >=0.12.1
        - scipy >=1.2.0,<2.0.0
      run_constrained:
        - esig ==0.9.7
        - filterpy >=1.4.5
        - hmmlearn >=0.2.7
        - gluonts >=0.9.0
        - matplotlib-base >=3.3.2
        - pmdarima >=1.8.0,!=1.8.1,<3.0.0
        - prophet >=1.1
        - pykalman >=0.9.5
        - pyod >=0.8.0
        - pystan ==2.19.1.1
        - scikit-posthocs >=0.6.5
        - seaborn >=0.11.0
        - statsforecast >=0.5.2
        - stumpy >=1.5.1
        - tbats >=1.1.0
        - tsfresh >=0.17.0
        - tslearn >=0.5.2
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - sktime
        - sktime.classification
        - sktime.datasets
        - sktime.distances
        - sktime.forecasting
        - sktime.performance_metrics
        - sktime.regression
        - sktime.series_as_features
        - sktime.transformations
        - sktime.utils

  - name: sktime-all-extras
    build:
      #FIXME: Extras environment not resolvable on aarch. Needs someone with
      #arm machine to tests.
      skip: true  # [aarch64]
      noarch: python
    requirements:
      run:
        - python
        - {{ pin_subpackage("sktime", max_pin='x.x.x') }}
        - cloudpickle
        - dask
        - dtw-python
        # - esig  # not on CF
        - filterpy
        - h5py
        # - hmmlearn  # not on CF
        # - gluonts  # not on CF
        - matplotlib-base
        - mne
        - pmdarima
        - prophet
        - pykalman
        - pyod
        - scikit-posthocs
        - seaborn
        - statsforecast
        - stumpy
        - tbats
        - tsfresh
        - tslearn
        - xarray

    test:
      imports:
        - sktime
        - sktime.classification
        - sktime.datasets
        - sktime.distances
        - sktime.forecasting
        - sktime.performance_metrics
        - sktime.regression
        - sktime.series_as_features
        - sktime.transformations
        - sktime.utils

about:
  home: https://github.com/alan-turing-institute/sktime
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A unified framework for machine learning with time series
  doc_url: https://www.sktime.org/en/latest/
  dev_url: https://github.com/alan-turing-institute/sktime

extra:
  recipe-maintainers:
    - fkiraly
    - dhirschfeld
    - freddyaboulton
    - lmmentel
    - mloning
