{% set name = "sktime" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alan-turing-institute/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 28e9dc87dfc0f859e9effea850d7504a40ece051be42b8e467bf0f2241e983d0

build:
  noarch: python
  number: 0
  skip: true  # [py>39]


outputs:
  - name: sktime
    script: build_script.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - llvm-openmp  # [osx]
      host:
        - python
        - deprecated >=1.2.13
        - cython >=0.29
        - numba >=0.53,<0.55
        - numpy 1.21.*
        - pandas >=1.1.0,<1.5.0
        - pip
        - setuptools
        - scikit-learn >=0.24.0
        - statsmodels >=0.12.1
        - wheel
      run:
        - python
        - deprecated >=1.2.13
        - {{ pin_compatible('numpy') }}
        - pandas >=1.1.0,<1.5
        - scikit-learn >=0.24.0
        - statsmodels >=0.12.1
        - numba >=0.50,<0.55
      run_constrained:
        - matplotlib-base >=3.3.2
        - pmdarima >=1.8.0,!=1.8.1
        - scikit-posthocs >=0.6.5
        - seaborn >=0.11.0
        - tsfresh >=0.17.0
        - hcrystalball >=0.1.9
        - stumpy >=1.5.1
        - prophet >=1.0
    test:
      imports:
        - sktime
        - sktime.classification
        - sktime.datasets
        - sktime.distances
        - sktime.forecasting
        - sktime.performance_metrics
        - sktime.regression
        - sktime.series_as_features
        - sktime.transformations
        - sktime.utils

  - name: sktime-all-extras
    requirements:
      run:
        - {{ pin_subpackage("sktime", max_pin="x.x.x.x") }}
        - matplotlib-base >=3.3.2
        - pmdarima >=1.8.0,!=1.8.1  # [not win and py<=38]
        - scikit-posthocs >=0.6.5
        - seaborn >=0.11.0
        - tsfresh >=0.17.0
        # - catch22 >=0.1.0
        - hcrystalball >=0.1.9
        - stumpy >=1.5.1
        # - tbats >=1.1.0
        - prophet >=1.0  # [py<=38]
        - python
    test:
      imports:
        - sktime
        - sktime.classification
        - sktime.datasets
        - sktime.distances
        - sktime.forecasting
        - sktime.performance_metrics
        - sktime.regression
        - sktime.series_as_features
        - sktime.transformations
        - sktime.utils

about:
  home: https://github.com/alan-turing-institute/sktime
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A unified framework for machine learning with time series
  doc_url: https://www.sktime.org/en/latest/
  dev_url: https://github.com/alan-turing-institute/sktime

extra:
  recipe-maintainers:
    - fkiraly
    - dhirschfeld
    - freddyaboulton
    - lmmentel
    - mloning
